### ISSUE TITLE
docker login gives error

### ISSUE THREAD

**Issue by CharanBR** [open-policy-agent/opa-docker-authz#24]
@tsandall ,

when I'm doing docker login, I get the prompt for entering username and password but immediately after that getting this error.

`Error response from daemon: plugin opa-docker-authz failed with error: AuthZPlugin.AuthZReq: unexpected end of JSON input`

Checking the docker logs and see this output and nothing else.

```
2018/05/18 17:25:37 Querying OPA policy data.docker.authz.allow. Input: {
  "AuthMethod": "",
  "Body": null,
  "Headers": {
    "User-Agent": "Docker-Client/17.09.1-ce (linux)"
  },
  "Method": "GET",
  "Path": "/_ping",
  "User": ""
}
2018/05/18 17:25:37 Returning OPA policy decision: true
2018/05/18 17:25:37 Querying OPA policy data.docker.authz.allow. Input: {
  "AuthMethod": "",
  "Body": null,
  "Headers": {
    "User-Agent": "Docker-Client/17.09.1-ce (linux)"
  },
  "Method": "GET",
  "Path": "/v1.32/info",
  "User": ""
}
2018/05/18 17:25:37 Returning OPA policy decision: true
```

**Comment by tsandall** [comment]
I think this means that the plugin is unable to serialize the input it received from Docker when the `login` command was executed. We ran into this before (https://github.com/open-policy-agent/opa-docker-authz/issues/12). This should be fixed in v0.2.1 and newer. Can you confirm that you're running v0.2.1 or newer?

If you are running v0.2.1 or newer and you're still seeing this error, we'll need to modify https://github.com/open-policy-agent/opa-docker-authz/blob/master/main.go#L111 to print the value of `r` so we can see the why the request is failing to serialize.

**Comment by CharanBR** [comment]
I'm running v0.2. let me upgrade to the latest and test again. Thanks for responding quickly.

**Comment by CharanBR** [comment]
upgraded it to v0.2.2 and that resolved the issue. Thank you so much.
